version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/frontend
    command: sh -c 'yarn start'
    ports:
      - '3000:3000'
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge
