version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/backend
    environment:
      - ENV_VARIABLE=example_value
    networks:
      - my_app_network
      
networks:
  my_app_network:
    driver: bridge

